### PR TITLE
Fix getting stuck and crashing

### PR DESCRIPTION
**Pull request by S2dentik**
* Fix getting stuck when sending multiple requests to `sourcekitd` simultaneously from different threads.
* Fix `SIGABRT` in SourceKitten when getting `substructure`.

### CODE REVIEW

**Comment by lexorus** [comment]
Checks are failing 😥. Tested on my machine too. 
This is because the test target settings are damaged and TaylorFrameworkTests cannot be launched. Check the changes in the settings, especially with `Yaml.framework` dependency.

**Comment by S2dentik** [comment]
#worksOnMyMachine

**Comment by lexorus** [comment]
@S2dentik did you tried to launch only TaylorFrameworkTests (by disabling TaylorIntegrationTests from the scheme)?

**Comment by lexorus** [comment]
@S2dentik ok, working now after update. Thanks 🎉🎉🎉.

**Review by lexorus — COMMENTED** [review]
LGTM

**Comment by thelvis4** [comment]
@S2dentik About dependencies:
Please use Carthage everywhere we can use it (for `SourceKitten` and all its dependencies).
In `TaylorFramework/Frameworks` we keep just the frameworks that don't support Carthage.

To do this:
1. Run `carthage update`
2. Link TaylorFramework against the binaries from `Carthage/Build/Mac`
3. Remove unnecessary frameworks from `TaylorFramework/Frameworks`

P.S. Current dependency management is not intuitive at all.

**Comment by thelvis4** [comment]
@S2dentik I made the suggested changes, so you don't have to worry about them.

Thanks for investigating and coming with the fix. 👍

**Pull request merged**
