### PR TITLE
Fix coding style inconsistencies

### PR DESCRIPTION
**Pull request by thelvis4**
This was made by running `swiftlint autocorrect` with 'trailing_whitespace' rule ignored.
A couple of manual changes had to be made after that (especially for 'if else' statements) .

### CODE REVIEW

**Comment by S2dentik** [comment]
These `conding styles` though...

**Comment by S2dentik** [comment]
Great job! 🍻 💯 Keep up

**Comment by S2dentik** [comment]
Just change the commit name please

**Comment by thelvis4** [comment]
Nice catch! 🙈

**Pull request merged**
