### PR TITLE
Delete unit test to check that codecov.io reports this change

### PR DESCRIPTION
**Pull request by thebugcode**
Please do not merge this PR, its only for confirming codecov.io works

### CODE REVIEW

**Comment by thelvis4** [comment]
Does this mean codecov doesn't work very accurate or I'm missing something?

**Comment by thelvis4** [comment]
No, I think the same lines were covered by the integration tests. Try to remove the integration tests. Then we'll see some nice diffs. :)

**Comment by thebugcode** [comment]
Nice catch. I commented out the integration test as well, waiting for the results

**Comment by thelvis4** [comment]
It works.
There are 60 lines of code that are covered by integration tests and are not covered by unit tests. :)

**Pull request closed without merging**
